# Generated by Django 5.2.6 on 2025-10-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_attendance_status_attendance_period1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period1_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period2_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period3_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period4_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period5_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period6_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period7_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='period1',
            field=models.CharField(default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='period2',
            field=models.CharField(default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='period3',
            field=models.CharField(default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='period4',
            field=models.CharField(default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='period5',
            field=models.CharField(default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='period6',
            field=models.CharField(default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='period7',
            field=models.CharField(default='Absent', max_length=10),
        ),
    ]
