# Generated by Django 5.2.7 on 2026-04-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_odform_staffprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to='dataset/'),
        ),
    ]
