# Generated by Django 5.2.7 on 2026-04-19 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_staffprofile_staff_id_staffprofile_staff_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('period1', models.CharField(default='Absent', max_length=10)),
                ('period2', models.CharField(default='Absent', max_length=10)),
                ('period3', models.CharField(default='Absent', max_length=10)),
                ('period4', models.CharField(default='Absent', max_length=10)),
                ('period5', models.CharField(default='Absent', max_length=10)),
                ('period6', models.CharField(default='Absent', max_length=10)),
                ('period7', models.CharField(default='Absent', max_length=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffprofile')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
