# Generated by Django 5.2.7 on 2026-04-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='odform',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.staffprofile'),
        ),
        migrations.AlterField(
            model_name='odform',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
