# Generated by Django 5.2.7 on 2026-04-19 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_odform_staff_alter_odform_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='staff_leave/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffprofile')),
            ],
        ),
    ]
