# Generated by Django 5.2.7 on 2026-04-28 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_staffleaveform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending Staff', 'Pending Staff'), ('Pending HOD', 'Pending HOD'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Staff', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentLeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='student_leave/')),
                ('status', models.CharField(choices=[('Pending Staff', 'Pending Staff'), ('Pending HOD', 'Pending HOD'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Staff', max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
